
--Nombre
--Apellido
--Cedula
--Teléfono
--Correo
--Foto de perfil
--Cursos


CREATE TABLE CURSO(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(140) NOT NULL
);


CREATE TABLE CLIENTE(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(140) NOT NULL,
	APELLIDO VARCHAR(140) NOT NULL,
	CEDULA VARCHAR(11) NOT NULL,
	TELEFONO VARCHAR(11),
	CORREO VARCHAR(140),
	URL_FOTO_PERFIL VARCHAR(140) NOT NULL,
	ID_CURSO INT NOT NULL,

	FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID)
);